#!/usr/bin/env bash
# Regenerate crates/executor/src/gen/cri_runtime_v1.rs from the pinned CRI
# runtime/v1 proto (crates/executor/proto/cri_runtime_v1.proto).
#
# The generated client for the Kata containerd backend is committed, so a
# normal build needs no protoc. This script is only for bumping the pinned
# CRI API version or re-syncing after an upstream change.
#
# Requirements: curl, cargo (network to crates.io), and a protoc binary.
# Point PROTOC at one, or put it on PATH:
#   export PROTOC=/path/to/protoc
#
# Usage:
#   scripts/regenerate-cri-api.sh            # regenerate from pinned tag
#   CRI_API_PIN=v0.38.0 scripts/regenerate-cri-api.sh   # bump the pin
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROTO_VENDORED="$REPO_ROOT/crates/executor/proto"
GEN_OUT="$REPO_ROOT/crates/executor/src/gen"
PIN="${CRI_API_PIN:-v0.37.0}"
PROTO_URL_BASE="https://raw.githubusercontent.com/kubernetes/cri-api/$PIN/pkg/apis/runtime/v1/api.proto"

# tonic-build / prost-build versions must match crates/executor/Cargo.toml.
TONIC_BUILD="0.12"
PROST_BUILD="0.13"

command -v protoc >/dev/null 2>&1 || test -n "${PROTOC:-}" || {
    echo "error: protoc not found. Set PROTOC=/path/to/protoc or install protoc." >&2
    exit 1
}

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

echo "==> fetching CRI runtime/v1 api.proto @ $PIN"
curl -sSfL --retry 3 -o "$PROTO_VENDORED/cri_runtime_v1.proto" "$PROTO_URL_BASE"

# Prepend the pin note (idempotent with the committed proto header).
PIN_NOTE="// Pinned: kubernetes/cri-api@$PIN, pkg/apis/runtime/v1/api.proto.
// Vendored verbatim (Apache-2.0, retained below). The generated Rust client
// (crates/executor/src/gen/cri_runtime_v1.rs) is regenerated from this file
// by scripts/regenerate-cri-api.sh. Do not edit by hand.

"
# shellcheck disable=SC2002
{ printf '%s' "$PIN_NOTE"; cat "$PROTO_VENDORED/cri_runtime_v1.proto"; } > "$TMP/proto.pin"
mv "$TMP/proto.pin" "$PROTO_VENDORED/cri_runtime_v1.proto"

echo "==> generating (tonic-build $TONIC_BUILD / prost-build $PROST_BUILD)"
mkdir -p "$TMP/proj/src" "$TMP/proto"
cp "$PROTO_VENDORED/cri_runtime_v1.proto" "$TMP/proto/"
cat > "$TMP/proj/Cargo.toml" <<EOF
[package]
name = "cri-regenerate"
version = "0.0.0"
edition = "2021"

[build-dependencies]
tonic-build = "$TONIC_BUILD"
prost-build = "$PROST_BUILD"
EOF
cat > "$TMP/proj/build.rs" <<EOF
fn main() {
    tonic_build::configure()
        .build_client(true)
        .build_server(false)
        .compile_protos(&["../proto/cri_runtime_v1.proto"], &["../proto"])
        .expect("tonic_build compile_protos");
}
EOF
echo 'fn main() {}' > "$TMP/proj/src/main.rs"

# prost-build names the generated module from the file's package (runtime.v1).
(cd "$TMP/proj" && PROTOC="${PROTOC:-protoc}" cargo build 2>&1)
GEN_SRC="$(find "$TMP/proj/target" -name "runtime.v1.rs" | head -1)"
test -n "$GEN_SRC" || { echo "error: generated runtime.v1.rs not found" >&2; exit 1; }

HEADER='// @generated by prost-build + tonic-build — DO NOT EDIT this file by hand.
// Source: kubernetes/cri-api@'"$PIN"' pkg/apis/runtime/v1/api.proto, vendored at
// crates/executor/proto/cri_runtime_v1.proto. Regenerate with
// scripts/regenerate-cri-api.sh (see that script for protoc requirements).
'
# shellcheck disable=SC2002
{ printf '%s' "$HEADER"; tail -n +3 "$GEN_SRC"; } > "$GEN_OUT/cri_runtime_v1.rs"

echo "==> wrote $GEN_OUT/cri_runtime_v1.rs ($(( $(wc -l < "$GEN_OUT/cri_runtime_v1.rs") )) lines)"
echo "remember: bump the CRI_API_PIN note in the committed proto header / generated file stays in sync"