{
 "title": "Vtessera",
 "tags": [ "vtessera" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "vtessera-node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Jobs Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vtessera_jobs_total{job=\"vtessera-node\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "vtessera_cpu_pct{job=\"vtessera-node\"} / 100",
     "legendFormat": "cpu_pct"
    }
   ]
  },
  { "title": "vtessera-offer-index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Offers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vtessera_offers_total{job=\"vtessera-offer-index\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Heartbeats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vtessera_heartbeats_total{job=\"vtessera-offer-index\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}